// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ActivateWorkspace(arg1:app.ActivateWorkspaceRequest):Promise<app.WorkspaceRecordInfo>;

export function CreateSpec(arg1:app.CreateSpecRequest):Promise<app.SpecNodeInfo>;

export function CreateTask(arg1:app.CreateTaskRequest):Promise<app.TaskInfo>;

export function CreateWorkspace(arg1:app.CreateWorkspaceRequest):Promise<app.WorkspaceRecordInfo>;

export function CurrentWorkspaceFolder():Promise<string>;

export function DeleteWorkspace(arg1:app.DeleteWorkspaceRequest):Promise<app.WorkspaceRegistryInfo>;

export function DetectAgentCLIs():Promise<Array<app.ProviderInfo>>;

export function ListWorkspaces():Promise<app.WorkspaceRegistryInfo>;

export function LoadActiveWorkspace():Promise<app.WorkspaceInfo>;

export function LoadWorkspace(arg1:string):Promise<app.WorkspaceInfo>;

export function Ping():Promise<string>;

export function SaveAutomation(arg1:app.SaveAutomationRequest):Promise<app.AutomationInfo>;

export function SelectWorkspaceFolder():Promise<any>;

export function StartNativeTerminal(arg1:app.NativeTerminalRequest):Promise<app.NativeTerminalSessionInfo>;

export function StopNativeTerminal(arg1:string):Promise<boolean>;

export function UpdateTaskStatus(arg1:app.UpdateTaskStatusRequest):Promise<app.TaskInfo>;

export function UpdateWorkspace(arg1:app.UpdateWorkspaceRequest):Promise<app.WorkspaceRecordInfo>;

export function UpsertRoutine(arg1:app.UpsertRoutineRequest):Promise<app.RoutineInfo>;
