// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function ActivateWorkspace(arg1:app.ActivateWorkspaceRequest):Promise<app.WorkspaceRecordInfo>;

export function BatchCreateTasks(arg1:app.BatchCreateTasksRequest):Promise<Array<app.TaskInfo>>;

export function CreateSpec(arg1:app.CreateSpecRequest):Promise<app.SpecNodeInfo>;

export function CreateTask(arg1:app.CreateTaskRequest):Promise<app.TaskInfo>;

export function CreateWorkspace(arg1:app.CreateWorkspaceRequest):Promise<app.WorkspaceRecordInfo>;

export function CommitTaskChanges(arg1:app.CommitTaskChangesRequest):Promise<app.TaskInfo>;

export function CurrentWorkspaceFolder():Promise<string>;

export function DeleteWorkspace(arg1:app.DeleteWorkspaceRequest):Promise<app.WorkspaceRegistryInfo>;

export function DetectAgentCLIs():Promise<Array<app.ProviderInfo>>;

export function FinishTaskTurn(arg1:app.FinishTaskTurnRequest):Promise<app.TaskInfo>;

export function ListWorkspaces():Promise<app.WorkspaceRegistryInfo>;

export function LoadActiveWorkspace():Promise<app.WorkspaceInfo>;

export function LoadWorkspace(arg1:string):Promise<app.WorkspaceInfo>;

export function Ping():Promise<string>;

export function PrepareTaskCommit(arg1:app.PrepareTaskCommitRequest):Promise<app.TaskInfo>;

export function ResizeNativeTerminal(arg1:app.NativeTerminalResizeRequest):Promise<void>;

export function ResumeTaskTurn(arg1:app.ResumeTaskTurnRequest):Promise<app.TaskInfo>;

export function RunTaskVerification(arg1:app.RunTaskVerificationRequest):Promise<app.TaskInfo>;

export function SaveAutomation(arg1:app.SaveAutomationRequest):Promise<app.AutomationInfo>;

export function SearchTasks(arg1:app.SearchTasksRequest):Promise<Array<app.TaskInfo>>;

export function SelectWorkspaceFolder():Promise<any>;

export function StartNativeTerminal(arg1:app.NativeTerminalRequest):Promise<app.NativeTerminalSessionInfo>;

export function StartTaskTurn(arg1:app.StartTaskTurnRequest):Promise<app.TaskInfo>;

export function StopNativeTerminal(arg1:string):Promise<boolean>;

export function UpdateTaskFlags(arg1:app.UpdateTaskFlagsRequest):Promise<app.TaskInfo>;

export function UpdateTaskStatus(arg1:app.UpdateTaskStatusRequest):Promise<app.TaskInfo>;

export function UpdateWorkspace(arg1:app.UpdateWorkspaceRequest):Promise<app.WorkspaceRecordInfo>;

export function UpsertRoutine(arg1:app.UpsertRoutineRequest):Promise<app.RoutineInfo>;

export function WriteNativeTerminal(arg1:app.NativeTerminalInputRequest):Promise<void>;
