// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateWorkspace(arg1) {
  return window['go']['app']['App']['ActivateWorkspace'](arg1);
}

export function BatchCreateTasks(arg1) {
  return window['go']['app']['App']['BatchCreateTasks'](arg1);
}

export function CommitTaskChanges(arg1) {
  return window['go']['app']['App']['CommitTaskChanges'](arg1);
}

export function CreateSpec(arg1) {
  return window['go']['app']['App']['CreateSpec'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['app']['App']['CreateTask'](arg1);
}

export function CreateWorkspace(arg1) {
  return window['go']['app']['App']['CreateWorkspace'](arg1);
}

export function CurrentWorkspaceFolder() {
  return window['go']['app']['App']['CurrentWorkspaceFolder']();
}

export function DeleteWorkspace(arg1) {
  return window['go']['app']['App']['DeleteWorkspace'](arg1);
}

export function DetectAgentCLIs() {
  return window['go']['app']['App']['DetectAgentCLIs']();
}

export function DispatchSpecs(arg1) {
  return window['go']['app']['App']['DispatchSpecs'](arg1);
}

export function FinishTaskTurn(arg1) {
  return window['go']['app']['App']['FinishTaskTurn'](arg1);
}

export function ListAgentProviders() {
  return window['go']['app']['App']['ListAgentProviders']();
}

export function ListAgentSessions(arg1) {
  return window['go']['app']['App']['ListAgentSessions'](arg1);
}

export function ListWorkspaceFiles(arg1) {
  return window['go']['app']['App']['ListWorkspaceFiles'](arg1);
}

export function ListWorkspaces() {
  return window['go']['app']['App']['ListWorkspaces']();
}

export function LoadActiveWorkspace() {
  return window['go']['app']['App']['LoadActiveWorkspace']();
}

export function LoadWorkspace(arg1) {
  return window['go']['app']['App']['LoadWorkspace'](arg1);
}

export function Ping() {
  return window['go']['app']['App']['Ping']();
}

export function PrepareTaskCommit(arg1) {
  return window['go']['app']['App']['PrepareTaskCommit'](arg1);
}

export function PreviewTaskDiff(arg1) {
  return window['go']['app']['App']['PreviewTaskDiff'](arg1);
}

export function ReadWorkspaceFile(arg1) {
  return window['go']['app']['App']['ReadWorkspaceFile'](arg1);
}

export function RegenerateOversight(arg1) {
  return window['go']['app']['App']['RegenerateOversight'](arg1);
}

export function ResizeNativeTerminal(arg1) {
  return window['go']['app']['App']['ResizeNativeTerminal'](arg1);
}

export function ResumeTaskTurn(arg1) {
  return window['go']['app']['App']['ResumeTaskTurn'](arg1);
}

export function RunRoutineScheduler(arg1) {
  return window['go']['app']['App']['RunRoutineScheduler'](arg1);
}

export function RunTaskVerification(arg1) {
  return window['go']['app']['App']['RunTaskVerification'](arg1);
}

export function SaveAutomation(arg1) {
  return window['go']['app']['App']['SaveAutomation'](arg1);
}

export function SearchTasks(arg1) {
  return window['go']['app']['App']['SearchTasks'](arg1);
}

export function SelectWorkspaceFolder() {
  return window['go']['app']['App']['SelectWorkspaceFolder']();
}

export function SendAgentInput(arg1) {
  return window['go']['app']['App']['SendAgentInput'](arg1);
}

export function StartAgentSession(arg1) {
  return window['go']['app']['App']['StartAgentSession'](arg1);
}

export function StartNativeTerminal(arg1) {
  return window['go']['app']['App']['StartNativeTerminal'](arg1);
}

export function StartTaskTurn(arg1) {
  return window['go']['app']['App']['StartTaskTurn'](arg1);
}

export function StopAgentSession(arg1, arg2) {
  return window['go']['app']['App']['StopAgentSession'](arg1, arg2);
}

export function StopNativeTerminal(arg1) {
  return window['go']['app']['App']['StopNativeTerminal'](arg1);
}

export function TriggerRoutine(arg1) {
  return window['go']['app']['App']['TriggerRoutine'](arg1);
}

export function UndoPlanningChange(arg1) {
  return window['go']['app']['App']['UndoPlanningChange'](arg1);
}

export function UpdateSpec(arg1) {
  return window['go']['app']['App']['UpdateSpec'](arg1);
}

export function UpdateTaskFlags(arg1) {
  return window['go']['app']['App']['UpdateTaskFlags'](arg1);
}

export function UpdateTaskStatus(arg1) {
  return window['go']['app']['App']['UpdateTaskStatus'](arg1);
}

export function UpdateWorkspace(arg1) {
  return window['go']['app']['App']['UpdateWorkspace'](arg1);
}

export function UpsertRoutine(arg1) {
  return window['go']['app']['App']['UpsertRoutine'](arg1);
}

export function WriteNativeTerminal(arg1) {
  return window['go']['app']['App']['WriteNativeTerminal'](arg1);
}

export function WriteWorkspaceFile(arg1) {
  return window['go']['app']['App']['WriteWorkspaceFile'](arg1);
}
